DEVICE          : cuda              # device used for training and evaluation (cpu, cuda, cuda0, cuda1, ...)
SAVE_DIR        : 'output'          # output folder name used for saving the model, logs and inference results

MODEL:
  NAME          : Mixprompt                                            # name of the model you are using
  BACKBONE      : Mixprompt-B5                                         # model variant
  PRETRAINED    : '/data/pretrained/segformer/mit_b5.pth'     # backbone model's weight 
  RESUME        : ''                                                # checkpoint file 

DATASET:
  NAME          : SUN                                          # dataset name to be trained with (camvid, cityscapes, ade20k)
  ROOT          : '/data/datasets/SUNRGBD'                            # dataset root path
  IGNORE_LABEL  : 0
  # MODALS        : ['img'] 
  MODALS        : ['img', 'depth']

TRAIN:
  IMAGE_SIZE    : [480, 640]      # training image size in (h, w) [480, 640]
  BATCH_SIZE    : 8               # batch size used to train
  EPOCHS        : 100             # number of epochs to train
  EVAL_START    : 0             # evaluation interval during training
  EVAL_INTERVAL : 1               # evaluation interval during training
  AMP           : false           # use AMP in training
  DDP           : true            # use DDP training

LOSS:
  NAME          : CrossEntropy     # loss function name
  CLS_WEIGHTS   : false            # use class weights in loss calculation

OPTIMIZER:
  NAME          : adamw           # optimizer name
  LR            : 0.005         # initial learning rate used in optimizer 0.04
  WEIGHT_DECAY  : 0.01           # decay rate used in optimizer 0.0005

SCHEDULER:
  NAME          : warmuppolylr    # scheduler name
  POWER         : 0.9             # scheduler power
  WARMUP        : 10              # warmup epochs used in scheduler
  WARMUP_RATIO  : 0.1             # warmup ratio
  

EVAL:
  MODEL_PATH    : ''
  # MODEL_PATH    : '/home/xiaozhongyu/pretrained/segformer/mit_b4.pth'
  
  IMAGE_SIZE    : [480, 640]      # evaluation image size in (h, w)                       
  BATCH_SIZE    : 16               # batch size used to train
  MSF: 
    ENABLE      : false                                    # multi-scale and flip evaluation  
    FLIP        : true                                    # use flip in evaluation  
    SCALES      : [0.5, 0.75, 1.0, 1.25, 1.5, 1.75]       # scales used in MSF evaluation                
